Updated documentation
radiantlogic-cfs/oidc-test-tool pull request #2
Opened 2024-04-22 13:58 UTC by emanuelvintila

2024-04-22 15:42 UTC, sgurusamy-rli requested changes
Documentations look great.
Other minor observation in examples:
1. There are Authorize request examples are different from Autorization Code flow and other flows. Can we have that updated to reflect HTTP Status 200 and HTTP status 302, on cases with consent screen and after consent screen.
2. In 302 response, the response contains code and session_state, it must be code and state. Verify and have this updated.
3. Can we update the documentation under Validations folder to "**All requests in this folder's subfolders captures cases when your requests could possibly fail.** The purpose is to demonstrate the expected error responses in those cases.
The folders are grouped by flow type. 
Each subfolder under a flow type represents a different case why a request would fail.
See the tests in the Tests tab of each request to see what the expected errors are for each case." 
4. Add descriptions for the subfolders under Validations, with a line or two explaining what are covered under these folders.
5. Add descriptions for the requests which are not under any folders like Get OIDC metadata, Refresh Token...(the requests at the end of the collection)

2024-04-23 13:25 UTC, emanuelvintila commented
Updated the collection to address the observations.

As for 3., the `state` is present in the response, as well as the `sesssion_state`
> When the OP supports session management, it MUST also return the Session State as an additional session_state parameter in the Authentication Response
> \- https://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions

2024-04-23 14:34 UTC, sgurusamy-rli commented
> Updated the collection to address the observations.
> 
> As for 3., the `state` is present in the response, as well as the `sesssion_state`
> 
> > When the OP supports session management, it MUST also return the Session State as an additional session_state parameter in the Authentication Response
> > - https://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions

For #4 and #5: 
* For the validation subfolders not all of them have description. 
* I see you have added bulleted points to the parent folder "Common", move those bullets to individual requests and for folders "Authorize" and "Token" - add descriptions like:
"Authorize" - Validations for Authorize endpoint
"Token"  - Validations for Token endpoint

2024-04-24 16:17 UTC, sgurusamy-rli approved these changes

2024-04-24 16:17 UTC, merged